name: dingtalk
version: 0.0.2
inputs:
- name: FLOWCI_DING_TOKEN
  type: string
  required: true

script: |
  WORK_DIR = ${FLOWCI_AGENT_PLUGIN_PATH}/dingtalk
  npm install ${WORK_DIR}
  node ${WORK_DIR}/dingtalk.js
